### ISSUE TITLE
Issue : Start Player Freezes the app

### ISSUE THREAD

**Issue by tanvi-iosdev** [Canardoux/flutter_sound#762]
## Flutter Sound Version : 7.8.4

When play button click flutter app freezes until audio starts playing.
This is happening in only Android app, iOS app doesn't freeze
Can anyone provide the solution?

**Start Player Code**
-----

`Future<void> startPlayer(String url) async {
    try {
      if (url != null) {
        await _ChatState.playerModule.startPlayer(
            fromURI: url,
            codec: Codec.aacMP4,
            whenFinished: () {
              stopPlayer();
            });
      }
    } catch (err) {
      print('error: $err');
    }
  }`

**Flutter Doctor**
------ 

`[✓] Flutter (Channel unknown, 1.22.6, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-GB)
    • Flutter version 1.22.6 at /Volumes/Workspace/Software/flutter
    • Framework revision 9b2d32b605 (8 months ago), 2021-01-22 14:36:39 -0800
    • Engine revision 2f0af37152
    • Dart version 2.10.5

[✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2)
    • Android SDK at /Users/pavans/Library/Android/sdk
    • Platform android-30, build-tools 30.0.2
    • ANDROID_HOME = /Users/pavans/Library/Android/sdk
    • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
    • All Android licenses accepted.

[✓] Xcode - develop for iOS and macOS (Xcode 12.1)
    • Xcode at /Volumes/Workspace/Software/iOS/xCode/12.1/Xcode.app/Contents/Developer
    • Xcode 12.1, Build version 12A7403
    • CocoaPods version 1.10.1

[✓] Android Studio (version 4.1)
    • Android Studio at /Applications/Android Studio.app/Contents
    • Flutter plugin installed
    • Dart plugin version 201.9306
    • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)

[✓] VS Code (version 1.60.0)
    • VS Code at /Applications/Visual Studio Code.app/Contents
    • Flutter extension version 3.25.0

[✓] Connected device (2 available)`

**Comment by Larpoux** [comment]
Someone already is asking that Flutter Sound does not wait all the song to be downloaded, and starts the playback during the download. (I am not able to tell you which issue number, but perhaps you can find this issue).
I am sure that it is something that we must improve : some users wants to playback very large files and the download is sometimes very slow.

This issue is very high in the TODO stack. I would be very glad if someone does something for that soon.

**Comment by rockyaussizz** [comment]
yes . its the issue , please provide the solution , UI freezes in Android , when start player

**Comment by rockyaussizz** [comment]
> ## Flutter Sound Version : 7.8.4
> When play button click flutter app freezes until audio starts playing. This is happening in only Android app, iOS app doesn't freeze Can anyone provide the solution?
> 
> ## **Start Player Code**
> `Future<void> startPlayer(String url) async { try { if (url != null) { await _ChatState.playerModule.startPlayer( fromURI: url, codec: Codec.aacMP4, whenFinished: () { stopPlayer(); }); } } catch (err) { print('error: $err'); } }`
> 
> ## **Flutter Doctor**
> `[✓] Flutter (Channel unknown, 1.22.6, on Mac OS X 10.15.5 19F101 darwin-x64, locale en-GB) • Flutter version 1.22.6 at /Volumes/Workspace/Software/flutter • Framework revision 9b2d32b605 (8 months ago), 2021-01-22 14:36:39 -0800 • Engine revision 2f0af37152 • Dart version 2.10.5
> 
> [✓] Android toolchain - develop for Android devices (Android SDK version 30.0.2) • Android SDK at /Users/pavans/Library/Android/sdk • Platform android-30, build-tools 30.0.2 • ANDROID_HOME = /Users/pavans/Library/Android/sdk • Java binary at: /Applications/Android Studio.app/Contents/jre/jdk/Contents/Home/bin/java • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495) • All Android licenses accepted.
> 
> [✓] Xcode - develop for iOS and macOS (Xcode 12.1) • Xcode at /Volumes/Workspace/Software/iOS/xCode/12.1/Xcode.app/Contents/Developer • Xcode 12.1, Build version 12A7403 • CocoaPods version 1.10.1
> 
> [✓] Android Studio (version 4.1) • Android Studio at /Applications/Android Studio.app/Contents • Flutter plugin installed • Dart plugin version 201.9306 • Java version OpenJDK Runtime Environment (build 1.8.0_242-release-1644-b3-6915495)
> 
> [✓] VS Code (version 1.60.0) • VS Code at /Applications/Visual Studio Code.app/Contents • Flutter extension version 3.25.0
> 
> [✓] Connected device (2 available)`

have you get any solution ? , i also need solution for this

**Comment by rockyaussizz** [comment]
> Someone already is asking that Flutter Sound does not wait all the song to be downloaded, and starts the playback during the download. (I am not able to tell you which issue number, but perhaps you can find this issue). I am sure that it is something that we must improve : some users wants to playback very large files and the download is sometimes very slow.
> 
> This issue is very high in the TODO stack. I would be very glad if someone does something for that soon.

please provide the solution for app UI freeze in android , when startPlayer called

**Comment by Larpoux** [comment]
Hi my friend,

I told you that I will explain how to develop/debug the Android or iOS code.
There is a very basic documentation [here](https://tau10.canardoux.xyz/tau_dev.html), but is not uptodate. For example what is called `tau_core` in the documentation is now called `tau_native` in Tau Sound 9.0.

## 1. restore all your config files 

For example your build.gradle scripts. It is important that all the config files are exactly as it was in the git repository, because my scripts does many `sed` commands and expect to have unmodified scripts.

## 2. Fork the github project [tau_native](https://github.com/Canardoux/tau_native)

This project contains all the iOS and Android code.
If you look to [this diagram](https://tau10.canardoux.xyz/architecture.html), tau_native is documented as `tau_core` in the bottom of the diagram

## 3. Add this fork as a submodule of your `tau10` fork

I am not a git expert, but you will find on Google how to create a submodule in a git project.
What is important for me, is that you will have a directory `tau10/tau_native` with all the native code.

## 4. bin/reldev DEV

```
cd tau10
bin/reldev.sh DEV
```
This script is to set a development environment.
This is this script which for example change your build.gradle files.
As I wrote a few lines above, it is important that all your config files are not modified directely by you

## 5. bin/flavor.sh LITE

This script is to set a LITE flavor of your configuration files.
I suggest that you use the LITE flavor and not the FULL flavor, because you are currently not working on FFmpeg

## 6. Flutter pub get

Under tau10/tau_sound/example

## 6. Cocoapod

Cocoapod is a little painful tool. It is possible that you must reset your Podifles : 
- cd tau10/tau_sound/example/ios
- rm Podfile.lock
- pod install --repo-update

**Comment by Larpoux** [comment]
If you plan to work on this issue : 

1. First you want to understand the Issue as entered by Tau Sound users : 
- Is really the App frozen during the download ? (no UI during the download). If this is the bug, then it means that the download is done on the main thread without running the Flutter main loop
- Or is the problem that the playback does not begin until all the sound is downloaded ?

2. You need to understand the processing flow that Tau Sound execute.
I am going to write a documentation of this flow, today, and I will post you the URL

**Comment by Larpoux** [comment]
The Android Sources : 

The main source of the player is tau10/tau_native/android/src/main/java/xyz/canardoux/TauNative/FlautoPlayer.java.

Line 203, we instanciate the FlautoEngine: 

```java
				player = new FlautoPlayerMedia(this);
```

The low level class for our Media Player is : tau10/tau_native/android/src/main/java/xyz/canardoux/TauNative/FlautoPlayerMedia.java.
Line 49, we ask Android to prepare the playback : 
```java
		mediaPlayer.setOnPreparedListener(mp -> {flautoPlayer.play(); flautoPlayer.onPrepared();});
```

Line 310 of tau10/tau_native/android/src/main/java/xyz/canardoux/TauNative/FlautoPlayer.java

we give the final completion indication to the dart side. (see the doc that I am preparing for you)


# NOTE: 

When I read the code, it seems that we do not download ourself the file, but just ask Android to play the remote URL.
If I am right, this is a very good news:

As I told you in another post, your task is
- Check that Android do not freeze the UI during the `prepare()` line 52 of FlautoPlayerMedia.java

I think that it is not possible to execute `flautoPlayer.play();` (in the callback line 49) before. For example juste after the
`mediaPlayer.prepare();` line 52. Android will not be Happy because you may not run `play` before the end of `prepare`.
	}

**Comment by Larpoux** [comment]
> * You need to understand the processing flow that Tau Sound execute.
>   I am going to write a documentation of this flow, today, and I will post you the URL
> *

[here it is](https://tau10.canardoux.xyz/processing_flow.html).
Please, tell me if it makes sense for you.

**Comment by Larpoux** [comment]
If you run macos, just do : 
```brew install gsed```

(of course you need to install brew. But a Mac developer cannot live without brew)

**Comment by Larpoux** [comment]
When I run Windows, I always install linux on it, to have a descent shell (and not cmd.com and other disgusting Windows tools)

**Comment by Larpoux** [comment]
WSL is very convenient

**Comment by Larpoux** [comment]
Cygwin is also a very good product, to have a descent shell.
But if you install Ubuntu under WSL you probably do not need cygwin

**Comment by Alvarocda** [comment]
So, i tryed Cygwin and a sed package from chocolatey and this happens when i try to run
![Sem título](https://user-images.githubusercontent.com/12532704/136664169-efba9a4e-dc1d-45e4-87fb-b565442adeef.png)

And in WSL, i have this
![image](https://user-images.githubusercontent.com/12532704/136664261-4d813664-4c59-4144-8711-202787a9e69d.png)


This is my tau10 folder
![image](https://user-images.githubusercontent.com/12532704/136664316-05d6921e-ee4f-4980-9219-32ea5a010b6a.png)

**Comment by Alvarocda** [comment]
Ok, i removed all CRs from the file and then i tried to run

it gives me the same erros as in windows, gsed is not found
![image](https://user-images.githubusercontent.com/12532704/136664724-8b1b4e6a-4892-4bed-978a-3f00eddc60fa.png)

i renamed gsed to only sed in reldev.sh and now it gives me the same error message as windows
![image](https://user-images.githubusercontent.com/12532704/136664763-5c5a73d5-c706-4a9f-9cc8-a1d81d7bafe2.png)

**Comment by Larpoux** [comment]
try : 
```sh
sudo apt-get install gsed
```
Sous ubuntu

**Comment by Larpoux** [comment]
No, I am probably wrong.
On linux, sed is the GNU sed (gsed).

I thing that just an alias is OK : 
```sh
alias gsed 'sed'
```

**Comment by Larpoux** [comment]
Just ignore the errors on Podfile

**Comment by Larpoux** [comment]
The problems that you had after renaming "gsed" as "sed" is because you did not run your script under `tau10` but under `tau10/bin`

**Comment by Larpoux** [comment]
you must do : 
```sh
cd tau10
bin/reldev.sh DEV
```

**Comment by Alvarocda** [comment]
Okay, I deleted the clone I had and cloned the entire repository again.

I managed to run both scripts without errors (bin/reldev.sh DEV and bin/flavor.sh LITE)

However, I still can't run the app.

```
FAILURE: Build failed with an exception.

* Where:
Build file 'C:\dev\tau10\tau_sound\android\build.gradle' line: 57

* What went wrong:
A problem occurred evaluating project ':tau_sound'.
> Project with path ':tau_native' could not be found in project ':tau_sound'.
```

**Comment by Larpoux** [comment]
OK. This is my fault. I have something wrong in my scripts. Minute ...

**Comment by Larpoux** [comment]
in tau10/tau_sound/android/settings.gradle I wrote something wrong line 7

It should be : 
```
   project(':tau_native').projectDir = file('../../tau_native/android')

```

I am sorry

**Comment by Alvarocda** [comment]
> are you sure that you have checkout all the sources under tau10/tau_native ?
> 
> You must have a subproject `tau_native` correctly setup inside your directory tau10

i cloned the tau10 repository using
`git clone --recursive `

the content of tau_native folder inside my tau10 folder
![image](https://user-images.githubusercontent.com/12532704/136666970-5e928f4f-4ea8-43e0-b3c4-3684c6bb18f2.png)

when open tau_native with my git bash, it shows me the branch i am using (or tag)
![image](https://user-images.githubusercontent.com/12532704/136666976-82374618-5ad4-48ad-9e46-f1256871f24f.png)

**Comment by Larpoux** [comment]
> in tau10/tau_sound/android/settings.gradle I wrote something wrong line 7
> 
> It should be :
> 
> ```
>    project(':tau_native').projectDir = file('../../tau_native/android')
> ```
> 
> I am sorry

**Comment by Larpoux** [comment]
You can check tau10/tau_sound/example/android/settings.gradle

but I do not see why it would be wrong ...

**Comment by Larpoux** [comment]
OH :  do your run the example or something else ?

**Comment by Alvarocda** [comment]
> OH : do your run the example or something else ?

nope.
only flutter pub get and flutter clean inside example folder

**Comment by Larpoux** [comment]
OK. I am studying that. A moment please ...

**Comment by Larpoux** [comment]
I do not see.
The android libraries directories are declared inside the two settings.graddle : 
- one under tau_sound/android
- one under tau_sound/example/android

Graddle should be able to find the `tau_native` library



> * What went wrong:
> A problem occurred evaluating project ':tau_sound'.
> > Project with path ':tau_native' could not be found in project ':tau_sound'.

This is weird

**Comment by Larpoux** [comment]
Double check tau_sound/android/settings.graddle

If necessary, put a HARD path to tau_native/android (just to see if better)

**Comment by Alvarocda** [comment]
oops, o copied build.gradle and not settings.gradle, my mistake

**Comment by Larpoux** [comment]
OK, It's time for me to stop for today ( GMT+2 ).
Tak with you tomorrow.
Good luck

**Comment by Alvarocda** [comment]
Ok, here it's still afternoon  (14:47pm) (GMT -4) 😆

**Comment by Larpoux** [comment]
For me, Brazil is the country where was invented one of the three languages that I love.
The three languages that I love are : 
- Pascal
- LUA
- Smalltalk

**Comment by Alvarocda** [comment]
> For me, Brazil is the country where was invented one of the three languages that I love. The three languages that I love are :
> 
> * Pascal
> * LUA
> * Smalltalk

Seriously? I didn't know these languages were invented in Brazil.

I haven't had the opportunity to use any of these languages yet.

**Comment by Larpoux** [comment]
Just Lua.

Pascal is Swiss 
Lua is Brazil
Smalltalk is California

**Comment by Larpoux** [comment]
Good morning @Alvarocda ,

> I cloned the repository with the fixes you made today, but it seems like the problem with the module R continues

I am very sorry. I pushed on github the `tau10` project instead of `tau_native`. 👎 
It should be better now.

BTW:
I suggest that we use another tool to work together, because we are actually polluating #762.

- Something like [slack](https://app.slack.com/client/T01KLGWT7LY/C01JWMQ07JN) (which is Close source 👎 ),
- `Zoom` (which is also Close Source 👎 )
- Or another tool if you know something convenient for us

**Comment by Larpoux** [comment]
For your information : the `Lock` is a very powerful object.
If there is an Exception during the Lock processing and the Exception is propagated **ABOVE** (int the App itself), the Lock is correctly released before the Exception is fired int the App : this is really a **GREAT** plugin.

So, you must just verify that there is nothing blocking during ```var aFuture = myPlayer.play();```

**Comment by Larpoux** [comment]
I am going to look to that. Probably in one hour. Patience ....

Note : I am renaming the name of the project (tau10) as a simply `tau`.
tau10 was temporary.
I hope that that you are not having problems with this rename

**Comment by Larpoux** [comment]
> * if you just change prepare to prepareasync, the _play will not start

Can you check if the code inside `setOnPreparedListener` is called ?
If you say that the _play does not start, it is probably that this code is never executed.
(Or is executed in a bad thread).

You must understand why this code is not called by the OS.
Or if it is called but the code is incorrect

```java
        mediaPlayer.setOnPreparedListener(mp -> {flautoPlayer.play(); flautoPlayer.onPrepared();}); 
	mediaPlayer.setOnCompletionListener(mp -> flautoPlayer.onCompletion());
```
I cannot read this code. This is sophisticated JAVA. Too complicate for me. 👎 
You can try : 
```java
 mediaPlayer.setOnPreparedListener(mp -> flautoPlayer.onPrepared() );
```

And add `play()` inside `flautoPlayer.onPrepared`
And check that `onPrepared` is correctly called by the OS

**Comment by abeerrizvi** [comment]
Is there any update on the issue? This issue is still occurring on flutter_sound: ^9.2.13.

**Comment by patelnirav48** [comment]
@Larpoux @Alvarocda In Android, app still freezes and get crashed when user play audio. Could you please help on this.
